### ISSUE TITLE
what  is this and how can I help?

### ISSUE THREAD

**Issue by turtleDev** [ofpiyush/po#2]

**Comment by ofpiyush** [comment]
shit! I just removed you from the org thinking you would not be interested.

Should have checked issues first 😞 

This is an evaluator I'd started working on [@verloop](/verloop).

We later decided not to use it for various reasons and today I decided to start working on it again as a side project.

I'm not sure if writing an interpreter for a language with no decided grammar interests you.

I'll start making some issues over the weekend and label them with `help wanted` :)

**Comment by turtleDev** [comment]
I'm not sure yet, that's why I asked.
